### ISSUE TITLE
help my proxy getting kicked

### ISSUE THREAD

**Issue by r3x07** [JamesJGoodwin/wreckuests#1]
Proxy 189.51.126.4:58727 has been kicked from attack due to it's nonoperability
Proxy 123.249.93.104:9999 has been kicked from attack due to it's nonoperability
Proxy 189.51.96.226:48718 has been kicked from attack due to it's nonoperability
**and it doesnt stop saying that**

**Comment by abriginets** [comment]
Hello. When you see this message it means that your server could not connect to exact proxy server after a few retries in a row and algorhitm cuts the thread which is using this proxy in order to free some memory and CPU for other working threads. This is not your fault but proxy. 

There are two ways to fix this. The first one is to check your proxies before running a script. There are a lot of proxycheckers on the web though. The second one is to just comment the print line:
```python
if err_count >= 20:
	#print("Proxy " + ips[index] + " has been kicked from attack due to it's nonoperability")
	return
```
