### ISSUE TITLE
most proxies are dead

### ISSUE THREAD

**Issue by kattstof** [JamesJGoodwin/wreckuests#2]
like title says, most supplied are dead, will update and make a pull request in a few days

**Comment by m1lw0rm** [comment]
username:password in target is?

**Comment by sajjadintel** [comment]
how can we update proxy list?

**Comment by abriginets** [comment]
Hello, @kattstof @sajadabasi. You can grab some proxies from [HideMyName](https://hidemyna.me/en/proxy-list/?type=s&anon=234#list) manually. For more advanced usage I recommend to use [ProxyBroker](https://github.com/constverum/ProxyBroker), which I was thinking to implement in the new release since keeping proxies and user-agents fresh is a real pain in the *ss. However I can't provide any exact implementation date. Busy with other stuff right now. Probably by the end of the summer it'll be completed.
